### ISSUE TITLE
Error while executing

### ISSUE THREAD

**Issue by VivekTodur** [wjbmattingly/keyword-spacy#2]
Hi,

How to solve the following issue?
ValueError: [E002] Can't find factory for 'keyword_extractor' for language English (en)

**Comment by wjbmattingly** [comment]
It requires a model that can produce vectors. Is it possible you were using the blank model or using a small model that does not create vectors?

**Comment by sean-dss** [comment]
I am also getting the same error.

```
    import spacy
    nlp = spacy.load("en_core_web_md")
    nlp.add_pipe("keyword_extractor", last=True,
                     config={"top_n": 10, "min_ngram": 3, "max_ngram": 3,
                             "strict":True, "top_n_sent": 3})

```

**Comment by sean-dss** [comment]
Adding this import made it work:
```    
from keyword_spacy import KeywordExtractor
```

Got the idea from: https://github.com/explosion/spaCy/discussions/7378

**Comment by wjbmattingly** [comment]
Ah yes, you do need to import the class to load the component. Thanks for noting that. I will update the Readme
